//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class CHUNGTU
    {
        public System.Guid ID { get; set; }
        public string SCT { get; set; }
        public Nullable<System.DateTime> Ngay { get; set; }
        public string SCT2 { get; set; }
        public Nullable<System.DateTime> Ngay2 { get; set; }
        public Nullable<int> SoLuong { get; set; }
        public Nullable<double> TongTien { get; set; }
        public string GhiChu { get; set; }
        public string MaCTy { get; set; }
        public string MaDVi { get; set; }
        public string MaDVi2 { get; set; }
        public Nullable<bool> TrangThai { get; set; }
        public Nullable<System.DateTime> NgayTao { get; set; }
        public Nullable<int> NguoiTao { get; set; }
        public Nullable<System.DateTime> NgaySua { get; set; }
        public Nullable<int> NguoiSua { get; set; }
        public Nullable<System.DateTime> NgayXoa { get; set; }
        public Nullable<int> NguoiXoa { get; set; }
    }
}
