//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class HANGHOA
    {
        public string Code { get; set; }
        public string TenHang { get; set; }
        public string TenTat { get; set; }
        public string DVT { get; set; }
        public Nullable<double> DonGia { get; set; }
        public Nullable<int> XuatXu { get; set; }
        public Nullable<int> MaNCC { get; set; }
        public Nullable<bool> Disabled { get; set; }
    }
}
