//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class SYS_FUNC
    {
        public string FUNC_Code { get; set; }
        public int SORT { get; set; }
        public string MoTa { get; set; }
        public Nullable<bool> Isgroup { get; set; }
        public string Parent { get; set; }
        public Nullable<bool> Menu { get; set; }
        public string Tips { get; set; }
    }
}
