//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_HANGHOA
    {
        public string Code { get; set; }
        public string TenHang { get; set; }
        public string TenTat { get; set; }
        public string DVT { get; set; }
        public Nullable<double> DonGia { get; set; }
        public string MoTa { get; set; }
        public Nullable<int> MaXX { get; set; }
        public string MaNCC { get; set; }
        public Nullable<int> IDNhom { get; set; }
        public Nullable<System.DateTime> NgayTao { get; set; }
        public Nullable<int> NguoiTao { get; set; }
        public Nullable<bool> Disabled { get; set; }
    }
}
