//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_SYS_USER
    {
        public int IDUser { get; set; }
        public string Username { get; set; }
        public string Password { get; set; }
        public string HoVaTen { get; set; }
        public string MaCTy { get; set; }
        public string MaDVi { get; set; }
        public Nullable<bool> Disabled { get; set; }
        public Nullable<bool> Isgroup { get; set; }
    }
}
