//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_SYS_REPORT
    {
        public int RepCode { get; set; }
        public string MoTa { get; set; }
        public string TenRep { get; set; }
        public Nullable<bool> Visibled { get; set; }
        public Nullable<bool> TuNgay { get; set; }
        public Nullable<bool> ThangNam { get; set; }
        public Nullable<bool> MaCTy { get; set; }
        public Nullable<bool> MaDVi { get; set; }
    }
}
