//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class TONKHO
    {
        public System.Guid ID { get; set; }
        public Nullable<int> NamKy { get; set; }
        public Nullable<int> Nam { get; set; }
        public Nullable<int> Ky { get; set; }
        public string MaDVi { get; set; }
        public Nullable<int> SLDau { get; set; }
        public Nullable<int> SLNhap { get; set; }
        public Nullable<int> SLXuat { get; set; }
        public Nullable<int> SLCuoi { get; set; }
        public Nullable<double> ThanhTien { get; set; }
        public Nullable<System.DateTime> Ngay { get; set; }
    }
}
