//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class V_SYS_RIGHT_REP
    {
        public int RepCode { get; set; }
        public string MoTa { get; set; }
        public string TenRep { get; set; }
        public Nullable<bool> Visibled { get; set; }
        public int IDUser { get; set; }
        public string QUYEN { get; set; }
    }
}
